name: Pytest

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, dev-new]

jobs:
  build:
    runs-on: ${{ vars.TASK_RUNNER || 'ubuntu-latest' }}
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      PROJECT_NAME: "Project Name"
      SERVER_NAME: localhost
      SERVER_HOST: https://localhost
      FIRST_SUPERUSER: superuser@example.org
      FIRST_SUPERUSER_PASSWORD: "some password"
      CLIENT_NAME: localhost
      CLIENT_HOST: https://localhost
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install poetry
          git config --global credential.helper '!echo "username=${{ github.actor }}"; echo "password=${{ secrets.PACKAGES_PAT }}";'
          poetry install
      - name: Run tests
        run: |
          source venv/bin/activate
          mkdir ./tmp
          bash ./tests-start.sh
